name: Build with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Visual Studio Build Tools (MSVC 14.3)
        run: |
          choco install visualstudio2019buildtools --version=16.11.3
          choco install microsoft-build-tools --version=14.3
          # Cài các addon như Windows SDK, C++ build tools, etc.
          choco install windows-sdk-10.0
          choco install cmake
        shell: bash

      - name: Cache MSVC and Nuitka build dependencies
        uses: actions/cache@v3
        with:
          path: |
            C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.3
            C:\Users\runneradmin\.cache\pip
          key: ${{ runner.os }}-msvc-14.3-${{ hashFiles('**/build.txt') }}
          restore-keys: |
            ${{ runner.os }}-msvc-14.3-
            ${{ runner.os }}-

      - name: Increase Heap Size for MSVC
        run: |
          echo CL=/Zm8000 >> "%GITHUB_ENV%"
        shell: cmd

      - name: Verify environment variables
        run: |
          echo "CL variable: %CL%"
          echo "GITHUB_ENV content:"
          type "%GITHUB_ENV%"
        shell: cmd

      - name: Install dependencies from build.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r build.txt

      - name: Run Nuitka build script
        run: |
          python build.py

      - name: Archive build output
        run: |
          Compress-Archive -Path build/* -DestinationPath build_output.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-build
          path: build_output.zip
