name: Build Python Applications with Nuitka

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      # Check-out repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python 3.12 với retry
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Cố định Python 3.12
          architecture: 'x64'
          cache: 'pip'
          cache-dependency-path: build.txt

      # Install dependencies from build.txt
      - name: Install dependencies
        run: |
          pip install -r build.txt

      # Build Client App
      - name: Build Client Application
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: Client/main.py
          mode: standalone
          enable-plugins: |
            pyside6
            multiprocessing
            pkg-resources
          assume-yes-for-downloads: true
          disable-console: ${{ runner.os == 'Windows' }}
          output-dir: build/Client App

      # Build Monitoring Unit App
      - name: Build Monitoring Unit Application
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: Monitoring Unit/main.py
          mode: standalone
          enable-plugins: |
            pyside6
            multiprocessing
            pkg-resources
          assume-yes-for-downloads: true
          disable-console: ${{ runner.os == 'Windows' }}
          output-dir: build/Monitoring Unit App

      # Upload Client Artifact
      - name: Upload Client Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-Client-App
          path: |
            build/Client App/**
          include-hidden-files: true

      # Upload Monitoring Unit Artifact
      - name: Upload Monitoring Unit Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-Monitoring-Unit-App
          path: |
            build/Monitoring Unit App/**
          include-hidden-files: true