name: Build with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          vsversion: 2019        # Chọn phiên bản Visual Studio (ở đây là 2019)
          arch: amd64            # Chọn kiến trúc hệ thống (x64)
          toolset: 14.3          # Chọn phiên bản toolset VC++

      - name: Verify environment variables
        run: |
          echo "CL variable: %CL%"
          echo "GITHUB_ENV content:"
          type "%GITHUB_ENV%"
        shell: cmd

      - name: Install dependencies from build.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r build.txt

      - name: Run Nuitka build script
        run: |
          python build.py

      - name: Archive build output
        run: |
          Compress-Archive -Path build/* -DestinationPath build_output.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-build
          path: build_output.zip
