name: Build with Nuitka

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install MSVC Build Tools
        run: |
          choco install visualstudio2022buildtools --force --params "--add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --includeOptional"
      
      - name: Add MSVC to PATH
        run: |
          echo "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\*\bin\Hostx64\x64" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Increase Heap Size for MSVC
        run: |
          echo "CL=/Zm8000" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Install dependencies from build.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r build.txt

      - name: Disable clcache (if needed)
        run: |
          echo "USE_CLCACHE=0" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Run Nuitka build script
        run: |
          python build.py

      - name: Archive build output
        run: |
          Compress-Archive -Path build/* -DestinationPath build_output.zip

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-build
          path: build_output.zip
